{% set name = "openeo" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Open-EO/openeo-python-client/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ff94909c223cde78ab31067607a1ec3da2014b6f5812df1dee7504bf468f386e
#  git_url: https://github.com/Open-EO/openeo-python-client.git

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openeo-auth = openeo.rest.auth.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - deprecated >=1.2.12
    - numpy >=1.17.0
    - pandas >0.20.0
    - requests >=2.26.0
    - shapely >=1.6.4
    - xarray >=0.12.3

test:
  imports:
    - openeo
  requires:
    - pip
    - pytest >=4.5.0
    - pytest-runner
    - matplotlib-base
    - mock
    - requests-mock >=1.8.0
    - h5netcdf
    - netCDF4
    - geopandas
    - oschmod  # [win]
    - httpretty
    - time-machine
  source_files:
    - tests
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/Open-EO/openeo-python-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client Library for the openEO API. Allows you to interact with openEO backends from your own (local) Python environment.

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - soxofaan
